

data test;
	temp = "un-unk-2019";
	
	if temp ne "" then do;
		*** Get the Day, Month, and Year when dates are ceparated by "-" ***;
		if index(temp, "-") > 0 then do; 
			if length(temp) = 11 then do;
				DD = scan(temp, 1, "-");
				MM = scan(temp, 2, "-");
				YY = scan(temp, 3, "-");
			end;
			else if length(temp) = 8 then do;
				MM = scan(temp, 1, "-");
				YY = scan(temp, 2, "-");
			end;
			else if length(temp) = 5 then do;
				YY = strip(tranwrd(temp, "-", ""));
			end;
			else if length(temp) = 4 then YY = temp;
			else put "WARNING unknown address format temp=";
		end;
		if index(temp, "/") > 0 or index(temp,"\") > 0 then do;
			if index(temp,"\") > 0 then temp2 = tranwrd(temp, "\", "/");
			if length(temp2) = 11 then do;
				DD = scan(temp2, 1, "/");
				MM = scan(temp2, 3, "/");
			end;
			else if length(temp2) = 8 then do;
				MM = scan(temp2, 1, "/");
				YY = scan(temp2, 2, "/");
			end;
			else if length(temp2) = 5 then do;
				YY = strip(tranwrd(temp2, "/", ""));
			end;
			else if length(temp2) = 4 then YY = temp;
			else put "WARNING unknown address format temp=";
		end;
		if upcase(YY) not in: ("U") then do;
			if upcase(MM) not in: ("U") then do;
				if upcase(DD) not in: ("U") then do;
					ISODATE = catx("-", YY, MM, DD);
				end;
				else ISODATE = catx("-", YY, MM);
			end;
			else ISODATE = strip(YY);
		end;
		else put "WARNING Missing year, check data temp=";
	end;
run;